cards
Mandhularajitha/component-library pull request #2
Opened 2022-03-01 12:06 UTC by Mandhularajitha

2022-03-01 15:26 UTC, znjs requested changes

2022-03-01 15:26 UTC, znjs commented on cards.css
> +
suggestion: better to have it in a `reset.css` file and import here

2022-03-01 15:26 UTC, znjs commented on cards.css
> +    margin-bottom: 5px;
use `rem`s for responsiveness

2022-03-01 15:26 UTC, znjs commented on cards.css
> +    font-size: 16px;
use `rem`s for responsiveness

2022-03-01 15:26 UTC, znjs commented on cards.css
> +    margin-bottom: 20px;
use `rem`s for responsiveness

2022-03-01 15:26 UTC, znjs commented on cards.css
> +    margin-top: 10px;
use `rem`s for responsiveness

2022-03-02 06:49 UTC, Sindhu983 approved these changes

2022-03-02 07:33 UTC, MonikaJhingan approved these changes
The code looks good to be merged.

2022-03-02 09:03 UTC, merged