button
Mandhularajitha/component-library pull request #5
Opened 2022-03-01 16:50 UTC by Mandhularajitha

2022-03-01 17:23 UTC, manismk requested changes

2022-03-01 17:23 UTC, manismk commented on button.css
> +    box-shadow: rgb(211, 192, 192);
Use rem for Responsiveness

2022-03-01 17:23 UTC, manismk commented on button.css
> +    border-radius: 8%;
Be consistent in color values. Either use rgb or use hex code. Avoid using direct color names

2022-03-01 17:23 UTC, manismk commented on button.css
> +.button3 {
Instead of button1, button2 . Naming can be given as button-primary or button-blue.

2022-03-01 17:23 UTC, manismk commented on button.css
> +}
Avoid direct tag styling

2022-03-02 05:53 UTC, neetukumari4858 approved these changes

2022-03-02 06:48 UTC, Sindhu983 approved these changes

2022-03-02 09:01 UTC, merged